theme: jekyll-theme-minimal
title: [Introduction to Python and the Principles of Data Visualization ]
logo: radial.png
description: [A Tufts University DISC Workshop]
url: https://annahaensch.github.io/
